---
title: "Enpol_Regressions"
author: "Eduardo Zago"
date: "24/5/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

```{r, include=FALSE, echo=FALSE}
library(haven)
library(tidyverse)
library(sandwich)
library(stargazer)
library(fixest)
library(knitr)
```


```{r, include=FALSE}
# Paths
path_in <- "C:/Users/lalo-/Dropbox/Research/Prisons/Tesis/data/clean/"
path_out <- "C:/Users/lalo-/Dropbox/Research/Prisons/Tesis/data/clean/csvs/"
path_results <- "C:/Users/lalo-/Dropbox/Research/Prisons/Tesis/results/"
```

# Importing the data:

```{r}
base_final <- read.csv(paste0(path_out, "base_final.csv"))
```

```{r}
tab(base_final, rate_drain1)
```

Dependent outcomes statistics:


```{r}
library(RCT)
tab_outcomes <- base_final %>% 
  select(private, suicide_t, insecure, quant_food, qual_food, sick_food, dep_study) %>%
  balance_table(., "private") %>%
  rename(variables = variables1,
         m_public = Media_control1,
         m_private = Media_trat1,
         p_value = p_value1) %>%
  mutate(across(where(is.numeric), ~ round(.x, digits = 4))) 
```

```{r}
tab_outcomes |> select(variables, m_public, m_private) |> 
     mutate(across(where(is.numeric), ~ .x * 100)) |> 
     kable(col.names = c("Variables",
                      "Public", 
                      "Private"), format = "latex",
        booktabs = T, 
        caption = "Descriptive Statistics: Outcomes of Interest") 
```

First Regression:

```{r}
reg_rates_g <- lm(rate_goods1 ~ private, base_final)
se_g <- sqrt(diag(vcovHC(reg_rates_g, type="HC1")))

reg_rates_r <- lm(rate_drain1 ~ private, base_final)
se_r <- sqrt(diag(vcovHC(reg_rates_r, type="HC1")))

reg_rates_t <- lm(rate_toilet1 ~ private, base_final)
se_t <- sqrt(diag(vcovHC(reg_rates_t, type="HC1")))

reg_rates_s <- lm(rate_shower1 ~ private, base_final)
se_s <- sqrt(diag(vcovHC(reg_rates_s, type="HC1")))

reg_rates_w <- lm(rate_water1 ~ private, base_final)
se_w <- sqrt(diag(vcovHC(reg_rates_w, type="HC1")))

reg_rates_l <- lm(rate_light1 ~ private, base_final)
se_l <- sqrt(diag(vcovHC(reg_rates_l, type="HC1")))
```


Regression Table

```{r}
stargazer(reg_rates_g, reg_rates_r, reg_rates_t, reg_rates_s, reg_rates_w, reg_rates_l,
          title = "Ratings Specifications",
          dep.var.labels= c("Goods", "Drainage", "Toilets", "Showers", "Drinking Water", "Lights"),
          se = list(se_g, se_r, se_t, se_s, se_w, se_l))

```

Regression Table, Controls and fixed effects:

```{r}
reg_rates_g1 <- lm(rate_goods1 ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced +
                     married + single + separated + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                        factor(sex_or) + factor(CVE_ENT), base_final)

se_g1 <- sqrt(diag(vcovHC(reg_rates_g1, type="HC1")))

reg_rates_r1 <- lm(rate_drain1 ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced +
                     married + single + separated + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                        factor(sex_or) + factor(CVE_ENT), base_final)
se_r1 <- sqrt(diag(vcovHC(reg_rates_r1, type="HC1")))

reg_rates_t1 <- lm(rate_toilet1 ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_t1 <- sqrt(diag(vcovHC(reg_rates_t1, type="HC1")))

reg_rates_s1 <- lm(rate_shower1 ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_s1 <- sqrt(diag(vcovHC(reg_rates_s1, type="HC1")))

reg_rates_w1 <- lm(rate_water1 ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_w1 <- sqrt(diag(vcovHC(reg_rates_w1, type="HC1")))

reg_rates_l1 <- lm(rate_light1 ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_l1 <- sqrt(diag(vcovHC(reg_rates_l1, type="HC1")))

```

Table Controls Etc

```{r}
stargazer(reg_rates_g1, reg_rates_r1, reg_rates_t1, reg_rates_s1, reg_rates_w1, reg_rates_l1,
          title = "Ratings Specifications",
          dep.var.labels= c("Goods", "Drainage", "Toilets", "Showers", "Drinking Water", "Lights"),
          se = list(se_g1, se_r1, se_t1, se_s1, se_w1, se_l1))
```

Linear model

```{r}
reg_linear_1 <- lm(suicide_t ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced +
                     married + single + separated + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                        factor(sex_or) + factor(CVE_ENT), base_final)

se_l1 <- sqrt(diag(vcovHC(reg_linear_1, type="HC1")))

reg_linear_2 <- lm(insecure ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced +
                     married + single + separated + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                        factor(sex_or) + factor(CVE_ENT), base_final)
se_l2 <- sqrt(diag(vcovHC(reg_linear_2, type="HC1")))

reg_linear_3 <- lm(quant_food ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_l3 <- sqrt(diag(vcovHC(reg_linear_3, type="HC1")))

reg_linear_4 <- lm(qual_food ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_l4 <- sqrt(diag(vcovHC(reg_linear_4, type="HC1")))

reg_linear_5 <- lm(sick_food ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_l5 <- sqrt(diag(vcovHC(reg_linear_5, type="HC1")))

reg_linear_6 <- lm(dep_study ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT), base_final)
se_l6 <- sqrt(diag(vcovHC(reg_linear_6, type="HC1")))

```


```{r}
stargazer(reg_linear_1, reg_linear_2, reg_linear_3, reg_linear_4, reg_linear_5, reg_linear_6,
          title = "Other Results",
          dep.var.caption = "Dependent Variable",
          dep.var.labels = c("Suicide Thoughts", "Insecure", "Food Quantity", "Food Quality",
                             "Food Sickness", "Studying"),
          table.placement = "htbp",
          se = list(se_l1, se_l2, se_l3, se_l4, se_l5, se_l6))
```



Other Results:

```{r}

probit1 <- glm(data = base_final, suicide_t ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT),
              family = binomial(link = "probit"))

probit2 <- glm(data = base_final, insecure ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT),
              family = binomial(link = "probit"))

probit3 <- glm(data = base_final, quant_food ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT),
              family = binomial(link = "probit"))

probit4 <- glm(data = base_final, qual_food ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT),
              family = binomial(link = "probit"))

probit5 <- glm(data = base_final, sick_food ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT),
              family = binomial(link = "probit"))

probit6 <- glm(data = base_final, dep_study ~ private + age + afro + sentence + school + child +
                     children + income_prior + lit_read + lit_write + time_inc +
                     diabetes + hiv + covid + hypert + hep + divorced + re_offender +
                     drug_related.x + rape.x + hom_related.x + guns_related.x +
                     kidnap_related.x + org_crime.x +
                     married + single + separated + factor(sex_or) + factor(CVE_ENT),
              family = binomial(link = "probit"))
```

```{r}
## Marginal effects
```


```{r}
stargazer(probit1, probit2, probit3, probit4, probit5,
          header = F,
          type = "latex",
          title = "Other Results",
          dep.var.caption = "Dependent Variable",
          dep.var.labels = c("Suicide Thoughts", "Insecure", "Food Quantity", "Food Quality", "Food Sickness"),
          table.placement = "htbp",
          notes.label = "Notes:",
          notes = "$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01",
          notes.append = F)
```
